name: documentation

on: [push]
permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Publish maven package
        run: |
          mkdir repo
          ./gradlew -Dmaven.repo.local=${{github.workspace}}/repo publishToMavenLocal
      - name: Install dependencies
        run: |
          pip install -r docs/requirements.txt
      - name: Sphinx build
        run: |
          sphinx-build docs/source docs/build
      - name: Deploy javadocs and maven repo
        run: |
          cp -r build/docs/javadoc docs/build
          cp -r repo docs/build/
          cp Autopilot.json docs/build/
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/
          force_orphan: true
