name: documentation

on: [push]
permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Generate Javadoc
        run: |
          ./gradlew javadoc
      - name: Publish maven package
        run: |
          mkdir build/repo
          ./gradlew -Dmaven.repo.local=${{github.workspace}}/build/repo publishToMavenLocal
      - name: Install dependencies
        run: |
          pip install sphinx furo
      - name: Sphinx build
        run: |
          sphinx-build docs/source docs/build
      - name: Deploy javadocs and maven repo
        run: |
          cp -r build/docs/javadoc build/javadoc
          cp -r build/repo docs/repo
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/
          force_orphan: true
